USE SPRING_MVC_TRAINING;


CREATE TABLE T_SPRING_MEMBER (
    MEMBER_ID 		VARCHAR(20) PRIMARY KEY,
    PASSWD 			VARCHAR(1000),
	MEMBER_NM 		VARCHAR(50),
	SEX 			VARCHAR(10),
	BIRTH_DT 		VARCHAR(20),
	HP 				VARCHAR(20),
	SMSSTS_YN 		VARCHAR(20),
	EMAIL 			VARCHAR(20),
	EMAILSTS_YN 	VARCHAR(20),
	ZIPCODE 		VARCHAR(20),
	ROAD_ADDRESS 	VARCHAR(500),
	JIBUN_ADDRESS 	VARCHAR(500),
	NAMUJI_ADDRESS 	VARCHAR(500),
	JOIN_DT 		DATETIME,
	ETC 			VARCHAR(3000)
);

SELECT 
		* 
FROM 
		T_SPRING_MEMBER;

